### ISSUE TITLE
Unable to create new account records.

### ISSUE THREAD

**Issue by sunandini01** [trailheadapps/ebikes-lwc#129] opened 2020-01-23 15:35 UTC
![image](https://user-images.githubusercontent.com/19372931/72998026-8ea18300-3e40-11ea-8629-fb95b89bcb5d.png)

Hi, the account record page doesn't let me create a new account record. It gives a java.lang.Null pointer exception when only the name field's value is supplied. Please notice the screenshot of the image pasted here.

Even clearing the value of billing street field in existing account records doesn't let me save the update and the error message is not visible. I was doing this to check what the AccountMap component would look like when the value of markers is empty.

**Comment by pozil** [comment] 2020-01-23 17:03
Hi @sunandini01 the fact that you see a Java error indicates that there's a problem with the Salesforce Platform or our your org. This doesn't come from the ebikes sample app for sure.
Nevertheless, I tried that and I can't reproduce.
I suggest that you either recreate the scratch org and/or give it another try later.

I'll close this issue for now.

**Closed by pozil** 2020-01-23 17:03 UTC

**Comment by sunandini01** [comment] 2020-01-24 08:39
Thanks @pozil . Reinstalling worked. Not sure what was wrong then :)
